[package]
name = "eloelo_model"
version = "0.1.0"
authors = ["wazniak"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4.22"
serde = { version = "1", features = ["derive"] }
